name: Deploy preview

on:
  push:
    branches:
      - main

jobs:
  deploy-preview:
    name: Build html and deploy preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
            version: "0.4.8"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
    
      - name: Install the project
        run: uv sync
    
      - name: make html
        run: make html
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html